name: Windows RDP VM

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Informações do sistema
        shell: powershell
        run: |
          Write-Host "===== SISTEMA ====="
          Get-ComputerInfo | Select-Object `
            WindowsProductName,
            WindowsVersion,
            OsArchitecture

          Write-Host ""
          Write-Host "===== CPU ====="
          Get-CimInstance Win32_Processor |
            Select-Object Name, NumberOfCores, NumberOfLogicalProcessors

          Write-Host ""
          Write-Host "===== RAM ====="
          $ram = Get-CimInstance Win32_ComputerSystem
          "{0:N2} GB" -f ($ram.TotalPhysicalMemory / 1GB)

          Write-Host ""
          Write-Host "===== DISCO ====="
          Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='C:'" |
            Select-Object DeviceID,
              @{N="TotalGB";E={[math]::Round($_.Size/1GB,2)}},
              @{N="FreeGB";E={[math]::Round($_.FreeSpace/1GB,2)}}

      - name: Testar Hyper-V
        shell: powershell
        run: |
          Write-Host "===== HYPER-V ====="

          Get-WindowsOptionalFeature `
            -Online `
            -FeatureName Microsoft-Hyper-V-All |
            Select-Object FeatureName, State

      - name: Testar RDP
        shell: powershell
        run: |
          Write-Host "===== RDP ====="

          Get-Service TermService |
            Select-Object Name, Status, StartType

          Get-ItemProperty `
            "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" |
            Select-Object fDenyTSConnections
